version: '3'

dotenv: ['.env']

env:
  APP_VERSION: 0.0.1
  APP_PATH: ./dice_game_win_probability
  PYTHONPATH: "{{.PYTHONPATH}}:{{.PWD}}"

vars:

  COMMIT_SHA:
    sh: git rev-parse HEAD
  DATE:
    sh: date "+%Y-%m-%d %H:%M:%S"

tasks:

  lint:
    desc: Runs linter check
    cmd: ruff check .

  install-dependencies:
    desc: Install dependencies
    cmds:
      - task: install-project-dependencies
      - task: install-linter-dependencies
      - task: install-formatter-dependencies

  install-project-dependencies:
    desc: Install project dependencies
    cmd: pip install -r requirements.txt

  install-linter-dependencies:
    desc: Install linter with dependencies
    cmd: pip install -r requirements.linter.txt

  install-formatter-dependencies:
    desc: Install formatter with dependencies
    cmd: pip install -r requirements.formatter.txt

  test:
    cmd: pytest dice_game_win_probability/tests/unit

  generate-build-info:
    silent: true
    internal: true
    cmds:
      - echo "# AUTOGENERATED FILE. DO NOT EDIT!"                   > $APP_PATH/__build_info__.py
      - echo "" 								 		            >> $APP_PATH/__build_info__.py
      - echo "__version__ = \"$APP_VERSION\"" 		                >> $APP_PATH/__build_info__.py
      - echo "__built_at__ = \"{{.DATE}}\"" 		 		        >> $APP_PATH/__build_info__.py
      - echo "__commit_sha__ = \"{{.COMMIT_SHA}}\""	  	            >> $APP_PATH/__build_info__.py

  run:
    deps:
      - task: generate-build-info
    cmd: python dice_game_win_probability/__main__.py

  format:
    cmd: black .